language: javascript

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_74631b0d0741_key -iv $encrypted_74631b0d0741_iv -in iris_travis.enc -out .iris_travis -d

script:
  - chmod 600 .iris_travis
  - echo .iris_travis

after_success:
  - rsync --exclude=".*" --delete -vPre 'ssh -i .iris_travis -p 222 -o "StrictHostKeyChecking no"' . www-data@iris.skowron.biz:/var/www/osm.link/
